# Generated by Django 5.0.1 on 2024-03-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
