# Generated by Django 5.0.1 on 2024-03-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
