# Generated by Django 5.0.1 on 2024-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
    ]
