# Generated by Django 5.0.1 on 2024-03-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
