# Generated by Django 5.0.1 on 2024-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
